<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findUserByRoles()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('u')
            ->from('\UserBundle\Entity\User', 'u')
            ->innerJoin('u.userRoles', 'r', 'WITH', 'r.role = ?1')
            ->setParameter(1, 'ROLE_ADMIN');

 return $qb->getQuery()->getResult();
    }

}
