<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface
{
    public function findAdmins()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('u')
            ->from('\UserBundle\Entity\User', 'u')
            ->innerJoin('u.userRoles', 'r', 'WITH', 'r.role = ?1')
            ->setParameter(1, 'ROLE_ADMIN');

        return $qb->getQuery()->getResult();
    }

    public function findAnnuaire()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('u')
            ->from('\UserBundle\Entity\User', 'u')
            ->innerJoin('u.userRoles', 'r', 'WITH', $qb->expr()->orX(
                $qb->expr()->eq('r.role', '?1'),
                $qb->expr()->eq('r.role', '?2')))
            ->setParameter(1, 'ROLE_ADMIN')
            ->setParameter(2, 'ROLE_PRESS');

        return $qb->getQuery()->getResult();
    }

    public function loadUserByUsername($username)
    {
        return $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }

}
