<?php

namespace EventsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends EntityRepository
{
    public function findPastEvents() {
        return $this->createQueryBuilder('e')
            ->where('e.end < :now')
            ->setParameter('now', new \DateTime(), \Doctrine\DBAL\Types\Type::DATETIME)
            ->orderBy('e.start', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }

    public function findFutureEvents() {
        return $this->createQueryBuilder('e')
            ->where('e.end >= :now')
            ->setParameter('now', new \DateTime(), \Doctrine\DBAL\Types\Type::DATETIME)
            ->orderBy('e.start', 'ASC')
            ->getQuery()
            ->getResult()
        ;
    }

    public function findThreeNextEvents() {
        return $this->createQueryBuilder('e')
            ->where('e.end >= :now')
            ->setParameter('now', new \DateTime(), \Doctrine\DBAL\Types\Type::DATETIME)
            ->orderBy('e.start', 'ASC')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult()
        ;
    }
}
