<?php

namespace EventsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvTagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvTagsRepository extends EntityRepository
{
}
