<?php

namespace EventsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvtagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvtagsRepository extends EntityRepository
{
	public function findAll()
    {
        return $this->findBy(array(), array('libelle' => 'ASC'));
    }
}
