<?php

namespace EventsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationRepository extends EntityRepository
{

	public function findRegistration($id) {
        $qb = $this->getEntityManager()->createQueryBuilder();
            $qb->select('r')
            ->from('\EventsBundle\Entity\Registration', 'r')
            ->innerJoin('r.events', 'e', 'WITH', 'e.id = ?1')
            ->setParameter(1, $id);
		return $qb->getQuery()->getResult();
    }
}
